- name: install fish
  homebrew:
    name: fish
    state: latest

- name: add fish to default shells
  shell: echo '/usr/local/bin/fish' >> /etc/shells
  become: yes

- name: set as default shell
  shell: chsh -s /usr/local/bin/fish

- name: download fisherman
  shell: >
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
    warn=false

- name: install plugin
  shell: fisher install oh-my-fish/plugin-balias oh-my-fish/plugin-extract spin z

- name: setup prompt
  copy:
    src: prompt.fish
    dest: "~/.config/fish/functions/fish_prompt.fish"

- name: create shells directory
  file:
    path: "{{ shells_dir }}"
    state: directory

- name: setup useful scripts
  copy:
    src: "{{ item }}"
    dest: "{{ shells_dir }}/{{ item }}"
    mode: 0755
  loop:
    - br
    - java_env

- name: setup config.fish
  template:
    src: config.fish
    dest: "~/.config/fish/config.fish"
