- name: install fish
  homebrew:
    name: fish
    state: latest

- name: set as default shell
  shell: chsh -s /usr/local/bin/fish

- name: download fisherman
  shell: >
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
    warn=false

- name: install plugin
  shell: fisher install balias extract getopts spin z

- name: setup prompt
  template:
    src: prompt.fish
    dest: "~/.config/fish/functions/fish_prompt.fish"

- name: create shells directory
  file:
    path: "{{ shells_dir }}"
    state: directory

- name: setup git_branch.sh
  template:
    src: git_branch.sh
    dest: "{{ git_branch_path }}"
    mode: 0755

- name: setup config.fish
  template:
    src: config.fish
    dest: "~/.config/fish/config.fish"
