- name: check installed jdk
  stat:
    path: "{{ download_dir }}/{{ tar_file }}"
  register: installed_jdk

- name: install open jdk
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_dir }}/{{ tar_file }}"
  when: not installed_jdk.stat.exists

- name: unarchive
  shell: >
    cd "{{ download_dir }}" &&
    tar xvfz "{{ tar_file }}" &&
    sudo mv "{{ jdk_dir }}" /Library/Java/JavaVirtualMachines/
    warn=false
  when:
    - not ansible_check_mode
    - not installed_jdk.stat.exists
