# to find the meanings, run "defaults find ?"
# example "defaults find KeyRepeat"

- name: setup macOS defaults with root user
  become: yes
  shell: >
    nvram SystemAudioVolume=" " &&
    chflags nohidden /Volumes

- name: mkdir screencapture_dir
  file:
    path: "{{ screencapture_dir }}"
    state: directory

- name: setup macOS defaults
  shell: >
    defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false &&
    defaults write com.apple.CrashReporter DialogType -string "none" &&
    defaults write com.apple.dock launchanim -bool false &&
    defaults write com.apple.dashboard mcx-disabled -bool true &&
    defaults write com.apple.finder AppleShowAllFiles -bool true &&
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true &&
    defaults write com.apple.finder ShowStatusBar -bool true &&
    defaults write com.apple.finder ShowPathbar -bool true &&
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf" &&
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true &&
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true &&
    defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true &&
    defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true &&
    defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true &&
    chflags nohidden ~/Library &&
    defaults write com.apple.screencapture location ~/Desktop/screencapture/ &&
    defaults write NSGlobalDomain InitialKeyRepeat -int 15 &&
    defaults write NSGlobalDomain KeyRepeat -int 2 &&
    defaults write NSGlobalDomain com.apple.trackpad.scaling -int 3

- name: setup macOS defaults for trackpad
  shell: >
    defaults write "{{ item }}" TrackpadThreeFingerDrag -int 1
  loop:
    - com.apple.AppleMultitouchTrackpad
    - com.apple.driver.AppleBluetoothMultitouch.trackpad
