- name: install go
  homebrew:
    name: go
    state: latest
  environment:
    GOPATH: "{{ go_path }}"

- name: install tools
  shell: go get -u "{{ item }}"
  loop:
    - honnef.co/go/tools/cmd/staticcheck
    - github.com/rakyll/hey
    - github.com/rakyll/gotest
    - github.com/golang/protobuf/protoc-gen-go
    - github.com/mithrandie/csvq
  environment:
    GOPATH: "{{ go_path }}"

- name: install csvq
  shell: go install
  chdir: "{{ go_path }}/src/github.com/mithrandie/csvq"
  environment:
    GOPATH: "{{ go_path }}"
    GO111MODULE: on
