- name: install go
  homebrew:
    name: go
    state: latest
  environment:
    GOPATH: "~/go"

- name: install tools
  shell: go get -u "{{ item }}"
  loop:
    - honnef.co/go/tools/cmd/staticcheck
    - github.com/rakyll/hey
    - github.com/rakyll/gotest
    - github.com/golang/protobuf/protoc-gen-go
  environment:
    GOPATH: "~/go"
